#pragma once
#include <stdint.h>

// E820 Memory Map Entry structure generated by the BIOS
struct mem_map_entry{
    uint64_t base_addr;
    uint64_t region_length;
    uint32_t region_type;
    uint32_t acpi_attributes;
} __attribute__((packed));


void pmm_init(void);
void* pmm_alloc_block(void);
void pmm_free_block(void* physical_addr);
int get_used_memory(void);